#!/usr/bin/expect

log_user 0

set tach "../tach"
set known "known_lines.txt"

set red	    "\x1b\x5b\x31\x3b\x33\x31\x3b\x34\x30\x6d"
set green	"\x1b\x5b\x31\x3b\x33\x32\x3b\x34\x30\x6d"
set normal	"\x1b\x5b\x31\x3b\x30\x3b\x34\x30\x6d"

proc fail {} {
	global red
	global normal
	global failures
	puts [concat $red "Failure!" $normal "\n"]
	exit 1
}

proc pass {} {
	global green
	global normal
	#puts [concat $green "Pass." $normal "\n"]
	exit 0
}
