.Dd 8/6/18
.Dt TACH 1
.Sh NAME
.Nm tach
.Nd time execution, line-by-line
.Sh SYNOPSIS
.Nm
.Op Fl lp
.Ar command
.Op Ar arg0 ...
.Sh DESCRIPTION
The
.Nm
utility executes a given command, wrapping the output with a left margin that tracks the time taken for each line output.
.Pp
A list of flags and their descriptions:
.Bl -tag -width -indent
.It Fl l
Low bandwidth mode. This minimizes the number of unnecessary screen updates, rather than giving a rolling millisecond precision, only the final timestamp of a line is printed.
.It Fl p
Connect the child process using
.Fn pipe
rather than
.Fn posix_openpt .
By default,
.Fn posix_openpt
is used.
.El
.Pp
.Sh CAVEATS
.Nm
does not interpret escape codes, they are passed through to the terminal containing
.Nm .
Escape codes that manipulate horizontal positioning may break out of the pty.
.Pp
.Nm
is line buffered, and the buffer is as large as the width of the pty used to contain the child process.
In rare cases a child process might emit escape sequences that span the end of the line buffer, causing them to become mangled by the left-hand side timestamp of the next line.
Wide characters whose glyph-widths don't line up with their byte-widths can also cause lines to wrap short or long.
.Sh SEE ALSO
.Xr time 1
